spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.103.2.119:3306/mp?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456789

  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      #username: mongoUsername
      #password: mongoPassword
      database: mycol

logging:
  level:
    root: warn
    com.shawn.mybatisplusdemo.dao: trace
  pattern: console:'%p%m%n'

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
